# vim ft=yaml
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

python:
  - 3.7

before_install:
  - python -m pip install --upgrade pip
  - pip install flake8

script:
  - flake8 fmriprep_rodents wrapper
